services:
    matt.karma.controller:
        class: matt\karma\controller\main
        arguments:
            - '@config'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '%core.table_prefix%'

    matt.karma.listener:
        class: matt\karma\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '%core.table_prefix%'
            - '@config'
        tags:
            - { name: event.listener }
